name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.7.5
  - ansiwrap=0.8.4
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - async_generator=1.10
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=22.1.0
  - bleach=4.1.0
  - blinker=1.4
  - blosc=1.21.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates
  - cairo=1.16.0
  - certifi=2021.10.8
  - certipy=0.1.3
  - cffi=1.15.0
  - cfitsio=4.0.0
  - charset-normalizer=2.0.10
  - click=8.0.4
  - colorama=0.4.4
  - cryptography=36.0.1
  - curl=7.81.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.6
  - fftw=3.3.10
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.96
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - fribidi=1.0.10
  - gdal=3.4.1
  - gdk-pixbuf=2.42.6
  - geos=3.10.2
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - ghostscript=9.54.0
  - giflib=5.2.1
  - graphite2=1.3.13
  - graphviz=2.50.0
  - greenlet=1.1.2
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=3.4.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.3
  - imagemagick=7.1.0_26
  - importlib-metadata=4.10.1
  - importlib_resources=5.4.0
  - ipykernel=6.7.0
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter-offlinenotebook=0.2.2
  - jupyter-resource-usage=0.6.1
  - jupyter_client=7.1.2
  - jupyter_core=4.9.1
  - jupyter_server=1.13.4
  - jupyter_telemetry=0.1.0
  - jupyterhub-base=1.4.2
  - jupyterhub-singleuser=1.4.2
  - jupyterlab=3.2.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.2
  - kealib=1.4.14
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libdap4=3.20.6
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgdal=3.4.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=14.2
  - librsvg=2.52.5
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libuv=1.43.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mako=1.1.6
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mypy_extensions=0.4.3
  - nbclassic=0.3.5
  - nbclient=0.5.10
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - nodejs=14.18.3
  - notebook=6.3.0
  - nspr=4.32
  - nss=3.74
  - nteract_on_jupyter=2.1.3
  - numpy=1.21.5
  - oauthlib=3.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pamela=1.0.0
  - pandoc=2.17.0.1
  - pandocfilters=1.5.0
  - pango=1.48.10
  - papermill=2.3.4
  - parso=0.8.3
  - pathspec=0.9.0
  - pcre=8.45
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.3.1
  - pixman=0.40.0
  - pkg-config=0.29.2
  - platformdirs=2.5.1
  - poppler=22.01.0
  - poppler-data=0.4.11
  - postgresql=14.2
  - proj=8.2.1
  - prometheus_client=0.13.0
  - prompt-toolkit=3.0.24
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pycurl=7.44.1
  - pygments=2.11.2
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.7
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python-json-logger=2.0.1
  - python_abi=3.7
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.27.1
  - ruamel.yaml=0.17.19
  - ruamel.yaml.clib=0.2.6
  - send2trash=1.8.0
  - setuptools=60.5.0
  - six=1.16.0
  - sniffio=1.2.0
  - sqlalchemy=1.4.31
  - sqlite=3.37.0
  - stress-ng=0.13.06
  - tenacity=8.0.1
  - terminado=0.12.1
  - testpath=0.5.0
  - textwrap3=0.9.2
  - tiledb=2.6.2
  - tk=8.6.11
  - tomli=2.0.1
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typed-ast=1.5.2
  - typing_extensions=4.0.1
  - tzcode=2021e
  - tzdata=2021e
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
prefix: /srv/conda/envs/notebook
